services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=devmentor
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
